/* confdefs.h */
#define PACKAGE_NAME "GridLAB-D"
#define PACKAGE_TARNAME "gridlabd"
#define PACKAGE_VERSION "3.1.0"
#define PACKAGE_STRING "GridLAB-D 3.1.0"
#define PACKAGE_BUGREPORT "gridlabd@pnnl.gov"
#define PACKAGE_URL ""
#define PACKAGE "gridlabd"
#define VERSION "3.1.0"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define __EXTENSIONS__ 1
#define _ALL_SOURCE 1
#define _GNU_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define _TANDEM_SOURCE 1
#define HAVE_PTHREAD_PRIO_INHERIT 1
#define HAVE_PTHREAD 1
#define X_DISPLAY_MISSING 1
#define HAVE_ARPA_INET_H 1
#define HAVE_FCNTL_H 1
#define HAVE_FLOAT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MALLOC_H 1
#define HAVE_MALLOC_H 1
#define HAVE_MATH_H 1
#define HAVE_MEMORY_H 1
#define HAVE_MEMORY_H 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_SCHED_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_TIMEB_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_UNISTD_H 1
#define HAVE_WCHAR_H 1
#define restrict __restrict
#define HAVE_STDBOOL_H 1
#define STDC_HEADERS 1
#define HAVE___SYNC_BOOL_COMPARE_AND_SWAP 1
#define HAVE___SYNC_ADD_AND_FETCH 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_SYS_TIME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ALARM 1
#define HAVE_STDLIB_H 1
#define HAVE_REALLOC 1
#define HAVE_STRFTIME 1
#define HAVE_VPRINTF 1
#define HAVE_ALARM 1
#define HAVE_ATEXIT 1
#define HAVE_FLOOR 1
#define HAVE_FTIME 1
#define HAVE_GETCWD 1
#define HAVE_GETHOSTBYNAME 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_INET_NTOA 1
#define HAVE_MEMSET 1
#define HAVE_MKDIR 1
#define HAVE_POW 1
#define HAVE_PUTENV 1
#define HAVE_SELECT 1
#define HAVE_SETENV 1
#define HAVE_SOCKET 1
#define HAVE_SQRT 1
#define HAVE_STRCHR 1
#define HAVE_STRCSPN 1
#define HAVE_STRERROR 1
#define HAVE_STRPBRK 1
#define HAVE_STRRCHR 1
#define HAVE_STRSTR 1
#define HAVE_STRTOL 1
#define HAVE_TZSET 1
#define HAVE_ISFINITE 1
#define DYN_PROC_AFFINITY 1
#define HAVE_GET_NPROCS 1
#define HAVE_SCHED_SETAFFINITY 1
#define HAVE_SCHED_GETAFFINITY 1
#define HAVE_CPU_SET_T 1
#define HAVE_CPU_SET_MACROS 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define DLEXT ".so"
